{
  login: 'Fatitboo',
  id: 93975407,
  node_id: 'U_kgDOBZnzbw',
  avatar_url: 'https://avatars.githubusercontent.com/u/93975407?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Fatitboo',
  html_url: 'https://github.com/Fatitboo',
  followers_url: 'https://api.github.com/users/Fatitboo/followers',
  following_url: 'https://api.github.com/users/Fatitboo/following{/other_user}',
  gists_url: 'https://api.github.com/users/Fatitboo/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Fatitboo/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Fatitboo/subscriptions',
  organizations_url: 'https://api.github.com/users/Fatitboo/orgs',
  repos_url: 'https://api.github.com/users/Fatitboo/repos',
  events_url: 'https://api.github.com/users/Fatitboo/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Fatitboo/received_events',
  type: 'User',
  user_view_type: 'public',
  site_admin: false,
  name: 'Nguyễn Văn Phát',
  company: null,
  blog: '',
  location: null,
  email: '21522448@gm.uit.edu.vn',
  hireable: true,
  bio: null,
  twitter_username: 'PhatNguyen1603',
  notification_email: '21522448@gm.uit.edu.vn',
  public_repos: 22,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2021-11-09T08:44:23Z',
  updated_at: '2024-11-19T09:25:03Z'
}