# version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
