export const data_popular = [
  {
    id: 23,
    name: "Beginner Friendly",
    url: "https://devpost.com/hackathons?themes%5B%5D=Beginner+Friendly",
    formatted_current_usd_prize_amount: "$1,075,000",
    current_challenges_count: 85,
  },
  {
    id: 22,
    name: "Open Ended",
    url: "https://devpost.com/hackathons?themes%5B%5D=Open+Ended",
    formatted_current_usd_prize_amount: "$229,000",
    current_challenges_count: 43,
  },
  {
    id: 13,
    name: "Social Good",
    url: "https://devpost.com/hackathons?themes%5B%5D=Social+Good",
    formatted_current_usd_prize_amount: "$666,000",
    current_challenges_count: 42,
  },
  {
    id: 6,
    name: "Machine Learning/AI",
    url: "https://devpost.com/hackathons?themes%5B%5D=Machine+Learning%2FAI",
    formatted_current_usd_prize_amount: "$1,787,000",
    current_challenges_count: 39,
  },
  {
    id: 19,
    name: "Education",
    url: "https://devpost.com/hackathons?themes%5B%5D=Education",
    formatted_current_usd_prize_amount: "$150,000",
    current_challenges_count: 23,
  },
  {
    id: 17,
    name: "Low/No Code",
    url: "https://devpost.com/hackathons?themes%5B%5D=Low%2FNo+Code",
    formatted_current_usd_prize_amount: "$637,000",
    current_challenges_count: 22,
  },
  {
    id: 25,
    name: "Web",
    url: "https://devpost.com/hackathons?themes%5B%5D=Web",
    formatted_current_usd_prize_amount: "$202,000",
    current_challenges_count: 16,
  },
  {
    id: 16,
    name: "Health",
    url: "https://devpost.com/hackathons?themes%5B%5D=Health",
    formatted_current_usd_prize_amount: "$129,000",
    current_challenges_count: 10,
  },
  {
    id: 18,
    name: "Design",
    url: "https://devpost.com/hackathons?themes%5B%5D=Design",
    formatted_current_usd_prize_amount: "$9,800",
    current_challenges_count: 10,
  },
  {
    id: 28,
    name: "Databases",
    url: "https://devpost.com/hackathons?themes%5B%5D=Databases",
    formatted_current_usd_prize_amount: "$134,000",
    current_challenges_count: 8,
  },
  {
    id: 4,
    name: "Gaming",
    url: "https://devpost.com/hackathons?themes%5B%5D=Gaming",
    formatted_current_usd_prize_amount: "$472,000",
    current_challenges_count: 7,
  },
  {
    id: 1,
    name: "Blockchain",
    url: "https://devpost.com/hackathons?themes%5B%5D=Blockchain",
    formatted_current_usd_prize_amount: "$804,000",
    current_challenges_count: 6,
  },
  {
    id: 7,
    name: "IoT",
    url: "https://devpost.com/hackathons?themes%5B%5D=IoT",
    formatted_current_usd_prize_amount: "$400,000",
    current_challenges_count: 6,
  },
  {
    id: 21,
    name: "Enterprise",
    url: "https://devpost.com/hackathons?themes%5B%5D=Enterprise",
    formatted_current_usd_prize_amount: "$127,000",
    current_challenges_count: 6,
  },
];
